/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.loggers.view;

import br.com.loggers.controller.LoginController;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Dimension;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

import java.sql.SQLException;
import javax.swing.BoxLayout;
import javax.swing.UIManager;
import raven.glasspanepopup.GlassPanePopup;


/**
 *
 * @author Pichau
 */
public class View extends javax.swing.JFrame {

    public String name;
    boolean visible = false;
    public JPasswordField getjPasswordFieldSenha() {
        return jPasswordFieldSenha;
    }

    public JTextField getjTextFieldEmail() {
        return jTextFieldEmail;
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(View.class.getName());

    /**
     * Creates new form LoginView
     */
    public View() {
        initComponents();
        GlassPanePopup.install(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        root = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        dashboard = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        nameUser = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        menu = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        rootDashboard = new javax.swing.JPanel();
        ordem_servico = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel25 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        pendenteLabel = new javax.swing.JLabel();
        andamentoLabel = new javax.swing.JLabel();
        finalizadoLabel = new javax.swing.JLabel();
        AgendadaLabel = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        manutencoes = new javax.swing.JPanel();
        historico = new javax.swing.JPanel();
        relatorio = new javax.swing.JPanel();
        ativo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setSize(new java.awt.Dimension(1440, 810));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        root.setLayout(new java.awt.CardLayout());

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setPreferredSize(new java.awt.Dimension(1440, 810));
        login.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(23, 50, 62));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/server_image_svg.png"))); // NOI18N
        jPanel2.add(jLabel1, new java.awt.GridBagConstraints());

        login.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(540, 810));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(360, 384));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setAlignmentX(0.0F);
        jPanel5.setPreferredSize(new java.awt.Dimension(360, 80));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 28)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SGMP");
        jLabel2.setAlignmentX(0.5F);
        jLabel2.setPreferredSize(new java.awt.Dimension(81, 28));
        jPanel5.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("<html>Sistema de Gerenciamento<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;de Manutenção Predial</html>");
        jLabel3.setAlignmentX(0.5F);
        jPanel5.add(jLabel3);

        jPanel4.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(360, 186));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("E-mail");
        jLabel4.setFocusable(false);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel4.setPreferredSize(new java.awt.Dimension(49, 44));
        jPanel6.add(jLabel4);

        jTextFieldEmail.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        jTextFieldEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldEmail.setAlignmentX(0.0F);
        jTextFieldEmail.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(java.awt.Color.decode("#D0D5DD"), 3, true),
            javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8)
        )
    );
    jTextFieldEmail.setPreferredSize(new java.awt.Dimension(360, 20));
    jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldEmailActionPerformed(evt);
        }
    });
    jPanel6.add(jTextFieldEmail);

    jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabel5.setText("Senha");
    jLabel5.setPreferredSize(new java.awt.Dimension(48, 44));
    jPanel6.add(jLabel5);

    jPanel9.setBackground(new java.awt.Color(255, 255, 255));
    jPanel9.setAlignmentX(0.0F);
    jPanel9.setPreferredSize(new java.awt.Dimension(360, 20));
    jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.X_AXIS));

    jPasswordFieldSenha.setFont(new java.awt.Font("Poppins", 1, 15)); // NOI18N
    jPasswordFieldSenha.setToolTipText("");
    jPasswordFieldSenha.setAlignmentX(0.0F);
    jPasswordFieldSenha.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(java.awt.Color.decode("#D0D5DD"), 3, true),
        javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8)
    )
    );
    jPasswordFieldSenha.setPreferredSize(new java.awt.Dimension(135, 20));
    jPanel9.add(jPasswordFieldSenha);

    jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/eye.png"))); // NOI18N
    jButton3.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(java.awt.Color.decode("#D0D5DD"), 3, true),
        javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8)
    )
    );
    jButton3.setContentAreaFilled(false);
    jButton3.setPreferredSize(new java.awt.Dimension(40, 30));
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });
    jPanel9.add(jButton3);

    jPanel6.add(jPanel9);

    jPanel4.add(jPanel6);

    jPanel7.setBackground(new java.awt.Color(255, 255, 255));
    jPanel7.setAlignmentX(0.0F);
    jPanel7.setPreferredSize(new java.awt.Dimension(360, 120));
    jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.PAGE_AXIS));

    jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel6.setText("<html> </html>");
    jLabel6.setAlignmentX(1.0F);
    jPanel7.add(jLabel6);

    jButton1.setBackground(new java.awt.Color(60, 137, 166));
    jButton1.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
    jButton1.setForeground(new java.awt.Color(255, 255, 255));
    jButton1.setText("Entrar");
    jButton1.setAlignmentX(1.0F);
    jButton1.setMaximumSize(new java.awt.Dimension(360, 52));
    jButton1.setPreferredSize(new java.awt.Dimension(360, 52));
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });
    jPanel7.add(jButton1);

    jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel7.setText("<html></html>");
    jLabel7.setAlignmentX(1.0F);
    jPanel7.add(jLabel7);

    jButton2.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
    jButton2.setForeground(new java.awt.Color(60, 137, 166));
    jButton2.setAlignmentX(1.0F);
    jButton2.setBorderPainted(false);
    jButton2.setContentAreaFilled(false);
    jButton2.setFocusPainted(false);
    jButton2.setLabel("Esqueceu a senha?");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });
    jPanel7.add(jButton2);

    jPanel4.add(jPanel7);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
            .addContainerGap(102, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(78, 78, 78))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap(208, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(218, Short.MAX_VALUE))
    );

    login.add(jPanel3, java.awt.BorderLayout.EAST);

    root.add(login, "login");

    dashboard.setLayout(new java.awt.BorderLayout());

    header.setBackground(new java.awt.Color(60, 137, 166));
    header.setPreferredSize(new java.awt.Dimension(1440, 64));
    header.setLayout(new java.awt.BorderLayout());

    jLabel8.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(255, 255, 255));
    jLabel8.setText("SGMP");
    jLabel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
    header.add(jLabel8, java.awt.BorderLayout.LINE_START);

    jPanel1.setBackground(new java.awt.Color(60, 137, 166));
    jPanel1.setPreferredSize(new java.awt.Dimension(220, 100));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel17.setBackground(new java.awt.Color(60, 137, 166));
    jPanel17.setPreferredSize(new java.awt.Dimension(198, 32));
    jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.LINE_AXIS));

    nameUser.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
    nameUser.setForeground(new java.awt.Color(255, 255, 255));
    nameUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/user-3296.png"))); // NOI18N
    nameUser.setText("  Técnico - Mário");
    jPanel17.add(nameUser);

    jButton9.setBackground(new java.awt.Color(60, 137, 166));
    jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/chevron_down.png"))); // NOI18N
    jButton9.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
    jButton9.setBorderPainted(false);
    jButton9.setContentAreaFilled(false);
    jButton9.setFocusPainted(false);
    jPanel17.add(jButton9);

    jButton10.setBackground(new java.awt.Color(60, 137, 166));
    jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/notifica.png"))); // NOI18N
    jButton10.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
    jButton10.setBorderPainted(false);
    jButton10.setContentAreaFilled(false);
    jButton10.setFocusPainted(false);
    jPanel17.add(jButton10);

    jPanel1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, 198, 32));

    header.add(jPanel1, java.awt.BorderLayout.LINE_END);

    dashboard.add(header, java.awt.BorderLayout.PAGE_START);

    menu.setBackground(new java.awt.Color(255, 255, 255));
    menu.setMinimumSize(new java.awt.Dimension(0, 0));
    menu.setPreferredSize(new java.awt.Dimension(263, 746));
    menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel10.setBackground(new java.awt.Color(255, 255, 255));
    jPanel10.setPreferredSize(new java.awt.Dimension(183, 256));
    jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.Y_AXIS));

    jPanel11.setBackground(new java.awt.Color(255, 255, 255));
    jPanel11.setMaximumSize(new java.awt.Dimension(2147483647, 42));
    jPanel11.setPreferredSize(new java.awt.Dimension(183, 42));
    jPanel11.setLayout(new java.awt.BorderLayout());

    jLabel9.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
    jLabel9.setText("Menu");
    jPanel11.add(jLabel9, java.awt.BorderLayout.LINE_START);

    jPanel10.add(jPanel11);

    jPanel12.setBackground(new java.awt.Color(255, 255, 255));
    jPanel12.setPreferredSize(new java.awt.Dimension(183, 42));

    jButton4.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
    jButton4.setForeground(new java.awt.Color(60, 137, 166));
    jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Chart.png"))); // NOI18N
    jButton4.setText("  Ordens de Serviço");
    jButton4.setBorderPainted(false);
    jButton4.setContentAreaFilled(false);
    jButton4.setFocusPainted(false);
    jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jButton4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
    jPanel12.setLayout(jPanel12Layout);
    jPanel12Layout.setHorizontalGroup(
        jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel12Layout.setVerticalGroup(
        jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
    );

    jPanel10.add(jPanel12);

    jPanel13.setBackground(new java.awt.Color(255, 255, 255));
    jPanel13.setPreferredSize(new java.awt.Dimension(183, 42));

    jButton5.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
    jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Vector.png"))); // NOI18N
    jButton5.setText("  Manutenções");
    jButton5.setBorderPainted(false);
    jButton5.setContentAreaFilled(false);
    jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
    jPanel13.setLayout(jPanel13Layout);
    jPanel13Layout.setHorizontalGroup(
        jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel13Layout.setVerticalGroup(
        jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
    );

    jPanel10.add(jPanel13);

    jPanel14.setBackground(new java.awt.Color(255, 255, 255));
    jPanel14.setPreferredSize(new java.awt.Dimension(183, 42));

    jButton6.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
    jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Clock.png"))); // NOI18N
    jButton6.setText("  Logs de Sistema");
    jButton6.setBorderPainted(false);
    jButton6.setContentAreaFilled(false);
    jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jButton6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton6ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
    jPanel14.setLayout(jPanel14Layout);
    jPanel14Layout.setHorizontalGroup(
        jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel14Layout.setVerticalGroup(
        jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
    );

    jPanel10.add(jPanel14);

    jPanel15.setBackground(new java.awt.Color(255, 255, 255));
    jPanel15.setPreferredSize(new java.awt.Dimension(183, 42));

    jButton7.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
    jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Document.png"))); // NOI18N
    jButton7.setText("  Relatórios");
    jButton7.setBorderPainted(false);
    jButton7.setContentAreaFilled(false);
    jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jButton7.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton7ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
    jPanel15.setLayout(jPanel15Layout);
    jPanel15Layout.setHorizontalGroup(
        jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel15Layout.setVerticalGroup(
        jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
    );

    jPanel10.add(jPanel15);

    jPanel16.setBackground(new java.awt.Color(255, 255, 255));
    jPanel16.setPreferredSize(new java.awt.Dimension(183, 42));

    jButton8.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
    jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Box.png"))); // NOI18N
    jButton8.setText("  Ativos");
    jButton8.setBorderPainted(false);
    jButton8.setContentAreaFilled(false);
    jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jButton8.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton8ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
    jPanel16.setLayout(jPanel16Layout);
    jPanel16Layout.setHorizontalGroup(
        jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
    );
    jPanel16Layout.setVerticalGroup(
        jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
    );

    jPanel10.add(jPanel16);

    menu.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 220, 300));

    dashboard.add(menu, java.awt.BorderLayout.LINE_START);

    rootDashboard.setLayout(new java.awt.CardLayout());

    ordem_servico.setBackground(new java.awt.Color(255, 255, 255));
    ordem_servico.setLayout(new javax.swing.BoxLayout(ordem_servico, javax.swing.BoxLayout.Y_AXIS));

    jPanel25.setLayout(new java.awt.BorderLayout());

    jPanel22.setLayout(new javax.swing.BoxLayout(jPanel22, javax.swing.BoxLayout.Y_AXIS));

    jPanel18.setAlignmentX(0.0F);
    jPanel18.setPreferredSize(new java.awt.Dimension(1177, 150));
    jPanel18.setLayout(new java.awt.BorderLayout());

    jPanel23.setMinimumSize(new java.awt.Dimension(0, 0));
    jPanel23.setLayout(new java.awt.GridBagLayout());

    jPanel20.setLayout(new java.awt.BorderLayout());

    jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/botao_nova_ordem.png"))); // NOI18N
    jButton11.setBorderPainted(false);
    jButton11.setContentAreaFilled(false);
    jButton11.setFocusPainted(false);
    jPanel24.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

    jPanel20.add(jPanel24, java.awt.BorderLayout.EAST);

    jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.Y_AXIS));

    jLabel11.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
    jLabel11.setText("Dashboard ");
    jPanel8.add(jLabel11);

    jLabel12.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
    jLabel12.setText("Progresso e organização das ordens de serviço");
    jPanel8.add(jLabel12);

    jPanel20.add(jPanel8, java.awt.BorderLayout.WEST);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 50);
    jPanel23.add(jPanel20, gridBagConstraints);

    jPanel18.add(jPanel23, java.awt.BorderLayout.CENTER);

    jPanel22.add(jPanel18);

    jPanel19.setAlignmentX(0.0F);
    jPanel19.setMinimumSize(new java.awt.Dimension(0, 0));
    jPanel19.setPreferredSize(new java.awt.Dimension(1177, 200));
    jPanel19.setLayout(new java.awt.GridBagLayout());

    pendenteLabel.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
    pendenteLabel.setForeground(new java.awt.Color(255, 255, 255));
    pendenteLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pendentes.png"))); // NOI18N
    pendenteLabel.setText("<html><body style='text-align: center'>0<br>Pendentes");
    pendenteLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 0;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 35);
    jPanel19.add(pendenteLabel, gridBagConstraints);

    andamentoLabel.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
    andamentoLabel.setForeground(new java.awt.Color(255, 255, 255));
    andamentoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/em_andamento.png"))); // NOI18N
    andamentoLabel.setText("<html><body style='text-align: center'>0<br>Em andamento");
    andamentoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 0;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 35);
    jPanel19.add(andamentoLabel, gridBagConstraints);

    finalizadoLabel.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
    finalizadoLabel.setForeground(new java.awt.Color(255, 255, 255));
    finalizadoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/finalizados.png"))); // NOI18N
    finalizadoLabel.setText("<html><body style='text-align: center'>0<br>Finalizadas");
    finalizadoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 0;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 35);
    jPanel19.add(finalizadoLabel, gridBagConstraints);

    AgendadaLabel.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
    AgendadaLabel.setForeground(new java.awt.Color(255, 255, 255));
    AgendadaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/agendados.png"))); // NOI18N
    AgendadaLabel.setText("<html><body style='text-align: center'>0<br>Agendadas");
    AgendadaLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 0;
    jPanel19.add(AgendadaLabel, gridBagConstraints);

    jPanel22.add(jPanel19);

    jPanel21.setAlignmentX(0.0F);
    jPanel21.setPreferredSize(new java.awt.Dimension(1227, 130));
    jPanel21.setLayout(new java.awt.BorderLayout());

    jPanel26.setLayout(new javax.swing.BoxLayout(jPanel26, javax.swing.BoxLayout.Y_AXIS));

    jLabel10.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
    jLabel10.setText("Notificações recentes");
    jLabel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 50, 15, 1));
    jPanel26.add(jLabel10);

    jLabel13.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
    jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Document.png"))); // NOI18N
    jLabel13.setText("Nenhuma notificação recente");
    jLabel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 50, 1, 1));
    jPanel26.add(jLabel13);

    jPanel21.add(jPanel26, java.awt.BorderLayout.PAGE_START);

    jPanel22.add(jPanel21);

    jPanel25.add(jPanel22, java.awt.BorderLayout.NORTH);

    jPanel27.setAlignmentX(0.0F);
    jPanel27.setLayout(new java.awt.GridBagLayout());

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
        }
    ));
    jScrollPane2.setViewportView(jTable1);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 50);
    jPanel27.add(jScrollPane2, gridBagConstraints);

    jPanel25.add(jPanel27, java.awt.BorderLayout.CENTER);

    jScrollPane1.setViewportView(jPanel25);

    ordem_servico.add(jScrollPane1);

    rootDashboard.add(ordem_servico, "ordem_servico");

    manutencoes.setBackground(new java.awt.Color(204, 51, 255));

    javax.swing.GroupLayout manutencoesLayout = new javax.swing.GroupLayout(manutencoes);
    manutencoes.setLayout(manutencoesLayout);
    manutencoesLayout.setHorizontalGroup(
        manutencoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 1177, Short.MAX_VALUE)
    );
    manutencoesLayout.setVerticalGroup(
        manutencoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 746, Short.MAX_VALUE)
    );

    rootDashboard.add(manutencoes, "manutencoes");

    historico.setBackground(new java.awt.Color(102, 255, 51));

    javax.swing.GroupLayout historicoLayout = new javax.swing.GroupLayout(historico);
    historico.setLayout(historicoLayout);
    historicoLayout.setHorizontalGroup(
        historicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 1177, Short.MAX_VALUE)
    );
    historicoLayout.setVerticalGroup(
        historicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 746, Short.MAX_VALUE)
    );

    rootDashboard.add(historico, "historico");

    relatorio.setBackground(new java.awt.Color(153, 0, 153));

    javax.swing.GroupLayout relatorioLayout = new javax.swing.GroupLayout(relatorio);
    relatorio.setLayout(relatorioLayout);
    relatorioLayout.setHorizontalGroup(
        relatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 1177, Short.MAX_VALUE)
    );
    relatorioLayout.setVerticalGroup(
        relatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 746, Short.MAX_VALUE)
    );

    rootDashboard.add(relatorio, "relatorio");

    javax.swing.GroupLayout ativoLayout = new javax.swing.GroupLayout(ativo);
    ativo.setLayout(ativoLayout);
    ativoLayout.setHorizontalGroup(
        ativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 1177, Short.MAX_VALUE)
    );
    ativoLayout.setVerticalGroup(
        ativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 746, Short.MAX_VALUE)
    );

    rootDashboard.add(ativo, "ativo");

    dashboard.add(rootDashboard, java.awt.BorderLayout.CENTER);

    root.add(dashboard, "dashboard");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(root, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(root, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean resultado;
        if(getjTextFieldEmail().getText().matches("") || getjPasswordFieldSenha().getText().matches("")){
            GlassPanePopup.showPopup(new PopupView("Erro!", "Um ou mais campos obrigatórios não foram preenchidos."));
        } else{
            try{
                LoginController login = new LoginController();
                resultado = login.loginUsuario(this);
                name = login.getUser().getNome();
            }
            catch(SQLException sql){
                resultado = false;
                System.out.println(sql);
            }

            if(resultado){
                GlassPanePopup.showPopup(new PopupView("Login realizado", "Bem vindo!"));
                CardLayout card = (CardLayout) root.getLayout();
                card.show(root, "dashboard");
                nameUser.setText("Técnico - "+name);
            }
            else{
                GlassPanePopup.showPopup(new PopupView("Usuário não encontrado", "Verifique seu e-mail e senha."));
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (visible == false){
            visible = true;
            jPasswordFieldSenha.setEchoChar((char)0);
        } else{
            visible = false;
            jPasswordFieldSenha.setEchoChar('*');
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        CardLayout card = (CardLayout) rootDashboard.getLayout();
        card.show(rootDashboard, "ordem_servico");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        CardLayout card = (CardLayout) rootDashboard.getLayout();
        card.show(rootDashboard, "manutencoes");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        if(evt.getComponent().getWidth() < 800){
            menu.setPreferredSize(new Dimension(43, 746));
        } else{
            menu.setPreferredSize(new Dimension(263, 746));
        }
    }//GEN-LAST:event_formComponentResized

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        CardLayout card = (CardLayout) rootDashboard.getLayout();
        card.show(rootDashboard, "historico");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        CardLayout card = (CardLayout) rootDashboard.getLayout();
        card.show(rootDashboard, "relatorio");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        CardLayout card = (CardLayout) rootDashboard.getLayout();
        card.show(rootDashboard, "ativo");
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
    UIManager.setLookAndFeel( new FlatLightLaf() );
    } catch( Exception ex ) {
        System.err.println( "Failed to initialize LaF" );
    }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new View().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgendadaLabel;
    private javax.swing.JLabel andamentoLabel;
    private javax.swing.JPanel ativo;
    private javax.swing.JPanel dashboard;
    private javax.swing.JLabel finalizadoLabel;
    private javax.swing.JPanel header;
    private javax.swing.JPanel historico;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JPanel login;
    private javax.swing.JPanel manutencoes;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel nameUser;
    private javax.swing.JPanel ordem_servico;
    private javax.swing.JLabel pendenteLabel;
    private javax.swing.JPanel relatorio;
    private javax.swing.JPanel root;
    private javax.swing.JPanel rootDashboard;
    // End of variables declaration//GEN-END:variables
}
